services:
  installer:
    container_name: pheme_installer
    image: 'ghcr.io/pheme/pheme:${PHEME_VERSION:-latest}'
    volumes:
      - './:/installer'
    restart: 'no'
    entrypoint: docker_installer
    command: install
    privileged: true
