[program:php-worker]
command=php /var/pheme/www/bin/console queue:process --worker-name=app_worker_0
user=pheme
priority=600
numprocs=1
autostart=true
autorestart=true

stopasgroup=true
killasgroup=true

stdout_logfile=/proc/1/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/proc/1/fd/2
stderr_logfile_maxbytes=0
